test = {   'name': 'q21',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> 1 <= jobs_q1 <= 3\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> jobs_q1 == 1\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
